dist: bionic
language: php

php:
  - 7.3
  - 7.4

env:
  global:
    - setup=basic
  matrix:
    - laravel=^6.0
    - laravel=^7.0
    - laravel=^8.0
    - setup=stable laravel=^6.0
    - setup=stable laravel=^7.0
    - setup=stable laravel=^8.0
    - setup=lowest laravel=^6.0
    - setup=lowest laravel=^7.0
    - setup=lowest laravel=^8.0

install:
  - composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --no-suggest
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit

matrix:
  fast_finish: true
